name: CI/CD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**CMakeLists.txt'
      - '**.cmake'
      - '**.h'
      - '**.cc'
      - '**.cxx'
      - '**.py'
      - '**.yml'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linter (flake8+black)
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Lint with flake8 and black -l 160
      run: |
        python -m pip install -q flake8 black
        black --version
        flake8 .
        black -l 160 --check --diff .

  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        root: ["6.26.4"]
        include:
          - python: "3.10"
            root: "6.32.2"
          - python: "3.12"
            root: "6.34.4"

    runs-on: ubuntu-latest
    name: Compile (py${{ matrix.python }}, root${{ matrix.root }})

    steps:
    - uses: actions/checkout@master
      with:
        path: HiggsAnalysis/CombinedLimit # Required to match compile instructions
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python }}
        miniforge-version: latest
    - name: Install build environment
      shell: bash -l {0}
      run: |
        # Install dependencies (synchronize with cms-combine-feedstock recipe.yaml)
        mamba install -c conda-forge cmake python==${{ matrix.python }} pandas gsl root==${{ matrix.root }} boost-cpp eigen
    - name: Build
      shell: bash -l {0}
      run: |
        cmake -S HiggsAnalysis/CombinedLimit -B build -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_INSTALL_PYTHONDIR=lib/python${{ matrix.python }}/site-packages -DUSE_VDT=OFF -DBUILD_TESTS=ON
        cmake --build build --clean-first --parallel "$(nproc)"
        cmake --install build  # Install to conda prefix (unsafe but ok for CI)
    - name: Run tests
      shell: bash -l {0}
      # Check if executables and Python module works, and then run the test battery
      run: |
        combine --help > /dev/null
        text2workspace.py --help > /dev/null
        ulimit -s unlimited;
        ctest --test-dir build/test --output-on-failure
