name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 112x

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linter (flake8+black)
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint with flake8 and black
      run: |
        python -m pip install -q flake8 black
        flake8 .
        black -l 160 --check --diff .

  build:
    strategy:
      matrix:
        python: ["3.8"]
        root: ["6.22", "6.24"]
        include:
          # to deprecate (11_2_X py2)
          - python: "2.7.18"
            root: "6.22.0"
    runs-on: ubuntu-latest
    name: Compile (py${{ matrix.python }}, root${{ matrix.root }})

    steps:
    - uses: actions/checkout@master
      with:
        path: HiggsAnalysis/CombinedLimit # Required to match compile instructions
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: combine
    - name: Install build environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge python==${{ matrix.python }} pip root==${{ matrix.root }} gsl tbb vdt boost pcre eigen certifi[version='>=2017.4.17']
        cd HiggsAnalysis/CombinedLimit
        bash set_conda_env_vars.sh
    - name: Build
      shell: bash -l {0}
      run: |
        cd HiggsAnalysis/CombinedLimit
        make CONDA=1 -j 2
